import type { NextPage } from 'next'
import Head from 'next/head'
import DefaultLayout from "../layouts/DefaultLayout";
import dynamic from "next/dynamic";
// Import components
const Home = dynamic(() =>
    import('../components/templates/Home')
)
// @ts-ignore
const HomePage: NextPage = ({header,homeBanner,advantages = [],apartments = [],...props}) => {
  return (
      <>
        <Head>
          <title>Main page</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Home {...props}  homeBanner={homeBanner} advantages={advantages} apartments={apartments} />
      </>
  )
}
export const getStaticProps = async () => {
    try {
        const menu = [
            {
                id: 1,
                url: '/',
                text: 'Home'
            },
            {
                id: 2,
                url: '/catalog',
                text: 'Catalog'
            },
            {
                id: 3,
                url: '/contact',
                text: 'Contact'
            }
        ]
        const advantages = [
            {
                id: 1,
                img: '/images/organisms/Home/Advantages/portfolio.svg',
                title: 'Renting Made Simple',
                description: 'Browse the highest quality listings, apply online, sign your lease, and even pay your rent from any device.'
            },
            {
                id: 2,
                img: '/images/organisms/Home/Advantages/search.svg',
                title: 'Find Your Next Renter',
                description: 'Connect with millions of renters and lease your property 100% online'
            },
            {
                id: 3,
                img: '/images/organisms/Home/Advantages/hand.svg',
                title: 'Tips for Renters',
                description: 'Tips for Renters Find answers to all of your renting questions with the best renter’s guide in the galaxy.'
            }
        ]

        const apartments = Array(5).fill(0).map((e,i)=>({
            id: i,
            verified: true,
            ready: true,
            title: 'Confortable apartment',
            sleepingPlaces: 56,
            shower: 56,
            dimensions: 56,
            address: 'Metro Plaza Dr, Jersey City, NJ 07302, USA',
            slug: `apartment-${i}`,
            price: 500
        }))
        return {
            props: {
                header: {
                    menu,
                    headerLogo: '/images/atoms/Logo/LogoLight.svg',
                },
                homeBanner: {
                  img: '/images/organisms/Home/Banner/banner.jpg',
                  title: 'Discover Your New Home',
                  description: 'Helping 100 million renters find their perfect fit.'
                },
                advantages,
                apartments,
                error: "",
            }
        };
    } catch (error:any) {
        return {
            props: {
                header: {
                    menu: [],
                    headerLogo: '/images/atoms/Logo/LogoLight.svg',
                },
                homeBanner: null,
                actualApartments: null,
                advantages: [],
                apartments: [],
                error: error.toString()
            }
        };
    }
};
export default DefaultLayout(HomePage)
