import type { NextPage } from 'next'
import Head from 'next/head'

import DefaultLayout,{ getStaticProps} from "../layouts/DefaultLayout";
const Home: NextPage = () => {
  return (
      <>
        <Head>
          <title>Main page</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

      </>
  )
}
export const getStaticProps = async () => {
    try {
        const menu = [
            {
                id: 1,
                url: '/',
                text: 'Home'
            },
            {
                id: 2,
                url: '/catalog',
                text: 'Catalog'
            },
            {
                id: 3,
                url: '/contact',
                text: 'Contact'
            }
        ]

        return {
            props: {
                menu,
                headerLogo: '/images/atoms/Logo/LogoLight.svg',
                error: "",
            }
        };
    } catch (error:any) {
        return {
            props: {
                menu: [],
                headerLogo: '/images/atoms/Logo/LogoLight.svg',
                error: error.toString()
            }
        };
    }
};
export default DefaultLayout(Home)
