import type { NextPage } from 'next'
import Head from 'next/head'
import DefaultLayout from "../layouts/DefaultLayout";
import dynamic from "next/dynamic";
// Import components
const Home = dynamic(() =>
    import('../components/templates/Home')
)
// @ts-ignore
const HomePage: NextPage = ({homeBanner,...props}) => {
  return (
      <>
        <Head>
          <title>Main page</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Home {...props}  homeBanner={homeBanner} />
      </>
  )
}
export const getStaticProps = async () => {
    try {
        const menu = [
            {
                id: 1,
                url: '/',
                text: 'Home'
            },
            {
                id: 2,
                url: '/catalog',
                text: 'Catalog'
            },
            {
                id: 3,
                url: '/contact',
                text: 'Contact'
            }
        ]

        return {
            props: {
                header: {
                    menu,
                    headerLogo: '/images/atoms/Logo/LogoLight.svg',
                },
                homeBanner: {
                  img: '/images/organisms/Banner/banner.jpg',
                  title: 'Discover Your New Home',
                  description: 'Helping 100 million renters find their perfect fit.'
                },
                error: "",
            }
        };
    } catch (error:any) {
        return {
            props: {
                header: {
                    menu: [],
                    headerLogo: '/images/atoms/Logo/LogoLight.svg',
                },
                homeBanner: {
                    img: '/images/organisms/Banner/banner.jpg',
                    title: 'Discover Your New Home',
                    description: 'Helping 100 million renters find their perfect fit.'
                },
                error: error.toString()
            }
        };
    }
};
export default DefaultLayout(HomePage)
